#!/usr/bin/env python3
"""
Generate HIL_Firmware/include/track_data.h from tracks/*.yaml.

The firmware has no runtime file I/O, so we bake the cone arrays into a header
at build time with a tiny purpose-built parser (no PyYAML). Run with --check to
exit non-zero if the header is stale.
"""
import glob, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TRACKS_DIR = os.path.join(ROOT, "tracks")
OUT = os.path.join(ROOT, "HIL_Firmware", "include", "track_data.h")

POINT_RE = re.compile(r"\[\s*(-?[0-9.]+)\s*,\s*(-?[0-9.]+)\s*\]")


def parse_yaml(path):
    # Parse one track file. Returns (name, left_points, right_points).
    name = None
    sections = {"left": [], "right": []}
    cur = None
    for raw in open(path):
        line = raw.split("#", 1)[0].rstrip()
        if not line.strip():
            continue
        m = re.match(r"name:\s*(\S+)", line)
        if m:
            name = m.group(1)
            cur = None
            continue
        m = re.match(r"(left|right):\s*$", line)
        if m:
            cur = m.group(1)
            continue
        m = POINT_RE.search(line)
        if m and cur is not None:
            sections[cur].append((float(m.group(1)), float(m.group(2))))
            continue
        raise ValueError("%s: cannot parse line: %r" % (path, raw.rstrip()))
    if name is None:
        raise ValueError("%s: missing 'name:'" % path)
    if not sections["left"] or not sections["right"]:
        raise ValueError("%s: left/right cones must be non-empty" % path)
    return name, sections["left"], sections["right"]


def c_ident(name):
    return re.sub(r"[^A-Za-z0-9]", "_", name).upper()


def fmt_array(name_uc, side, pts):
    out = ["static const float %s_%s[][2] = {" % (name_uc, side)]
    line = ""
    for i, (x, y) in enumerate(pts):
        line += "{%10.4ff,%10.4ff}, " % (x, y)
        if (i + 1) % 3 == 0:
            out.append("    " + line.rstrip())
            line = ""
    if line:
        out.append("    " + line.rstrip())
    out.append("};")
    return "\n".join(out)


def render():
    files = sorted(glob.glob(os.path.join(TRACKS_DIR, "*.yaml")))
    if not files:
        raise SystemExit("gen_tracks.py: no tracks/*.yaml found")

    tracks = [parse_yaml(f) for f in files]

    L = []
    L.append("/* track_data.h - GENERATED by tools/gen_tracks.py from the track YAML files.")
    L.append(" * DO NOT EDIT BY HAND. Edit the YAML and rebuild (the Makefile runs the")
    L.append(" * generator). Included only by track_parser.c. */")
    L.append("#ifndef TRACK_DATA_H")
    L.append("#define TRACK_DATA_H")
    L.append("")
    L.append('#include "track_parser.h"')
    L.append("")

    for name, left, right in tracks:
        uc = c_ident(name)
        L.append("/* ---- %s (left=%d, right=%d) ---- */" % (name, len(left), len(right)))
        L.append(fmt_array(uc, "LEFT", left))
        L.append(fmt_array(uc, "RIGHT", right))
        L.append("")

    L.append("static const TrackLayout TRACK_DATA[] = {")
    for name, left, right in tracks:
        uc = c_ident(name)
        L.append('    { "%s", %s_LEFT, %d, %s_RIGHT, %d },'
                 % (name, uc, len(left), uc, len(right)))
    L.append("};")
    L.append("#define TRACK_DATA_COUNT ((int)(sizeof(TRACK_DATA) / sizeof(TRACK_DATA[0])))")
    L.append("")
    L.append("#endif /* TRACK_DATA_H */")
    return "\n".join(L) + "\n"


def main():
    text = render()
    check = "--check" in sys.argv[1:]
    existing = open(OUT).read() if os.path.exists(OUT) else None
    if check:
        if existing != text:
            print("gen_tracks.py: track_data.h is stale - run "
                  "`python tools/gen_tracks.py` and commit.", file=sys.stderr)
            sys.exit(1)
        print("track_data.h up to date")
        return
    if existing == text:
        return  # don't touch mtime so make doesn't rebuild needlessly
    with open(OUT, "w") as f:
        f.write(text)
    names = [parse_yaml(f)[0] for f in sorted(glob.glob(os.path.join(TRACKS_DIR, "*.yaml")))]
    print("gen_tracks.py: wrote %s (%d tracks: %s)"
          % (os.path.relpath(OUT, ROOT), len(names), ", ".join(names)))


if __name__ == "__main__":
    main()
